"""Shareable Markdown report output for Drift analysis results.

Generates a self-contained Markdown document suitable for:
- Sharing in GitHub issues/PRs
- Pasting into Slack or documentation
- Embedding in CI artifacts
- Archival and trend comparison
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from drift import __version__

if TYPE_CHECKING:
    from drift.models import Finding, RepoAnalysis

_SEVERITY_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🟢",
    "info": "⚪",
}


def _severity_icon(severity_value: str) -> str:
    return _SEVERITY_EMOJI.get(severity_value, "⚪")


def _format_score(score: float) -> str:
    if score <= 15:
        return f"**{score:.1f}** (healthy)"
    if score <= 35:
        return f"**{score:.1f}** (moderate drift)"
    if score <= 55:
        return f"**{score:.1f}** (significant drift)"
    return f"**{score:.1f}** (critical drift)"


def _finding_row(finding: Finding, rank: int) -> str:
    sev = _severity_icon(finding.severity.value)
    location = str(finding.file_path) if finding.file_path else ""
    if finding.start_line:
        location += f":{finding.start_line}"
    signal = finding.signal_type
    title = finding.title or finding.description[:80]
    return f"| {rank} | {sev} {finding.severity.value} | `{signal}` | `{location}` | {title} |"


def analysis_to_markdown(
    analysis: RepoAnalysis,
    *,
    max_findings: int = 30,
    include_preflight: bool = True,
    include_interpretation: bool = True,
) -> str:
    """Generate a shareable Markdown report from analysis results."""
    lines: list[str] = []

    # Header
    repo_name = analysis.repo_path.name
    lines.append(f"# Drift Analysis Report — `{repo_name}`")
    lines.append("")
    lines.append(
        f"> Generated by [drift](https://github.com/mick-gsk/drift) "
        f"v{__version__} on {analysis.analyzed_at.strftime('%Y-%m-%d %H:%M UTC')}"
    )
    lines.append("")

    # Score summary
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Drift Score | {_format_score(analysis.drift_score)} |")
    sev_icon = _severity_icon(analysis.severity.value)
    sev_val = analysis.severity.value
    lines.append(f"| Severity | {sev_icon} {sev_val} |")
    lines.append(f"| Files analysed | {analysis.total_files} |")
    lines.append(f"| Functions | {analysis.total_functions} |")
    lines.append(f"| AI-attributed ratio | {analysis.ai_attributed_ratio:.0%} |")
    lines.append(f"| Duration | {analysis.analysis_duration_seconds:.1f}s |")
    lines.append(f"| Status | {analysis.analysis_status} |")
    lines.append("")

    # Trend (if available)
    if analysis.trend and analysis.trend.delta is not None:
        delta = analysis.trend.delta
        delta_sign = "+" if delta >= 0 else ""
        lines.append(
            f"**Trend:** {delta_sign}{delta:.1f} ({analysis.trend.direction})"
        )
        lines.append("")

    # Preflight
    pf = getattr(analysis, "preflight", None)
    if include_preflight and pf is not None:
        lines.append("## Preflight Diagnostics")
        lines.append("")
        git_icon = "✅" if pf.git_available else "⚠️"
        lines.append(f"- {git_icon} Git: {'available' if pf.git_available else 'not found'}")
        lines.append(f"- 📁 {pf.python_files_found} Python files found")
        lines.append(f"- 🔍 {pf.active_count} signals active, {pf.skipped_count} skipped")
        if pf.skipped_signals:
            lines.append("")
            lines.append("**Skipped signals:**")
            lines.append("")
            for skip in pf.skipped_signals:
                lines.append(f"- **{skip.signal_id}** ({skip.signal_name}): {skip.reason}")
                lines.append(f"  - 💡 {skip.hint}")
        if pf.warnings:
            lines.append("")
            for warn in pf.warnings:
                lines.append(f"> ⚠️ {warn}")
        lines.append("")

    # Findings table
    findings = sorted(analysis.findings, key=lambda f: (
        {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}.get(f.severity.value, 5),
        -(f.impact or 0),
    ))
    total = len(findings)
    shown = findings[:max_findings]

    if shown:
        lines.append(f"## Findings ({total})")
        lines.append("")
        lines.append("| # | Severity | Signal | Location | Title |")
        lines.append("|---|----------|--------|----------|-------|")
        for i, f in enumerate(shown, 1):
            lines.append(_finding_row(f, i))
        if total > max_findings:
            lines.append(f"| | | | | *...and {total - max_findings} more* |")
        lines.append("")
    else:
        lines.append("## Findings")
        lines.append("")
        lines.append("✅ **No findings** — no structural coherence problems detected.")
        lines.append("")

    # Module scores
    if analysis.module_scores:
        lines.append("## Module Scores")
        lines.append("")
        lines.append("| Module | Score | Findings |")
        lines.append("|--------|-------|----------|")
        for m in sorted(analysis.module_scores, key=lambda x: -x.drift_score):
            lines.append(
                f"| `{m.path}` | {m.drift_score:.1f} | {len(m.findings)} |"
            )
        lines.append("")

    # Signal coverage
    if pf is not None:
        lines.append("## Signal Coverage")
        lines.append("")
        active_str = (
            ", ".join(f"`{s}`" for s in pf.active_signals)
            if pf.active_signals
            else "none"
        )
        lines.append(f"**Active:** {active_str}")
        if pf.skipped_signals:
            lines.append(
                f"**Skipped:** {', '.join(f'`{s.signal_id}`' for s in pf.skipped_signals)}"
            )
        lines.append("")

    # Analyzer warnings (signal-level)
    analyzer_warnings = getattr(analysis, "analyzer_warnings", [])
    skip_warnings = [w for w in analyzer_warnings if getattr(w, "skipped", False)]
    if skip_warnings:
        lines.append("## Analyzer Warnings")
        lines.append("")
        for w in skip_warnings:
            lines.append(f"- ⚠️ **{w.signal_type}**: {w.message}")
        lines.append("")

    # Degradation info
    if analysis.is_degraded:
        lines.append("## Degradation")
        lines.append("")
        lines.append(
            f"Analysis ran in **degraded** mode. "
            f"Causes: {', '.join(analysis.degradation_causes)}."
        )
        lines.append("")

    # Interpretation guidance
    if include_interpretation:
        lines.append("---")
        lines.append("")
        lines.append("*The drift score measures structural entropy, not code quality. "
                      "A rising score signals coherence loss — but temporary increases "
                      "during migrations or refactorings are expected. "
                      "Deliberate polymorphism (Strategy, Adapter, Plugin patterns) can "
                      "trigger MDS/PFS findings that reflect correct design, not erosion. "
                      "Use `drift trend` to track deltas over time.*")
        lines.append("")

    # Feedback prompt
    lines.append("---")
    lines.append("")
    lines.append(
        "📣 *Found a false positive or unexpected result? "
        "[File an issue](https://github.com/mick-gsk/drift/issues/new?"
        "template=false_positive.yml) to help improve drift.*"
    )
    lines.append("")

    return "\n".join(lines)
