"""Data models for the Architecture Graph."""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Any, Literal


@dataclass(slots=True)
class ArchModule:
    """A module (directory) in the architecture graph."""

    path: str
    drift_score: float
    file_count: int
    function_count: int
    responsibility: str | None = None
    layer: str | None = None
    primary_owner: str | None = None
    stability: float = 1.0
    signal_scores: dict[str, float] = field(default_factory=dict)
    languages: list[str] = field(default_factory=list)


@dataclass(slots=True)
class ArchDependency:
    """A dependency edge between two modules."""

    from_module: str
    to_module: str
    dep_type: str = "import"
    weight: int = 1
    policy: str | None = None


@dataclass(slots=True)
class ArchAbstraction:
    """A key abstraction (function/class) in the system vocabulary."""

    symbol: str
    kind: str  # "function" | "class" | "method"
    module_path: str
    file_path: str
    usage_count: int = 0
    consumers: list[str] = field(default_factory=list)
    has_docstring: bool = False
    is_exported: bool = False


@dataclass(slots=True)
class ArchHotspot:
    """A file or module with recurring drift findings over time."""

    path: str
    recurring_signals: dict[str, int] = field(default_factory=dict)
    trend: Literal["improving", "stable", "degrading"] = "stable"
    total_occurrences: int = 0


@dataclass(slots=True)
class ArchDecision:
    """A machine-readable architecture decision (Phase D).

    Decisions are matched by *scope* (glob pattern) against target paths
    during ``steer()`` to deliver constraints to AI agents.
    """

    id: str
    scope: str  # glob pattern (e.g. "src/api/**")
    rule: str  # human-readable constraint text
    enforcement: Literal["info", "warn", "block"] = "warn"
    source: str | None = None  # reference to ADR or doc
    active: bool = True


@dataclass(slots=True)
class PatternProposal:
    """A proposed architecture rule derived from recurring drift patterns.

    Phase E of the Architecture Runtime Blueprint.  Generated by the
    feedback loop when a signal recurs above threshold in a module.
    Status transitions: proposed → accepted | rejected (by maintainer).
    """

    pattern_type: str  # e.g. "recurring_signal", "boundary_violation"
    module_path: str
    signal_id: str
    occurrences: int
    proposed_decision: ArchDecision
    confidence: float
    status: Literal["proposed", "accepted", "rejected"] = "proposed"
    evidence_files: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-safe dictionary."""
        return {
            "pattern_type": self.pattern_type,
            "module_path": self.module_path,
            "signal_id": self.signal_id,
            "occurrences": self.occurrences,
            "proposed_decision": {
                "id": self.proposed_decision.id,
                "scope": self.proposed_decision.scope,
                "rule": self.proposed_decision.rule,
                "enforcement": self.proposed_decision.enforcement,
                "source": self.proposed_decision.source,
                "active": self.proposed_decision.active,
            },
            "confidence": self.confidence,
            "status": self.status,
            "evidence_files": list(self.evidence_files),
        }


@dataclass
class ArchGraph:
    """Top-level container for the living architecture model.

    Versioned by git commit SHA.  Persisted to .drift-cache/.
    """

    version: str
    modules: list[ArchModule] = field(default_factory=list)
    dependencies: list[ArchDependency] = field(default_factory=list)
    abstractions: list[ArchAbstraction] = field(default_factory=list)
    hotspots: list[ArchHotspot] = field(default_factory=list)
    decisions: list[ArchDecision] = field(default_factory=list)
    updated_at: float = field(default_factory=time.time)

    # -- query helpers -------------------------------------------------------

    def get_module(self, path: str) -> ArchModule | None:
        """Return module by path, or *None*."""
        for m in self.modules:
            if m.path == path:
                return m
        return None

    def neighbors(self, module_path: str) -> list[str]:
        """Return all modules connected to *module_path* (either direction)."""
        result: set[str] = set()
        for d in self.dependencies:
            if d.from_module == module_path:
                result.add(d.to_module)
            elif d.to_module == module_path:
                result.add(d.from_module)
        return sorted(result)

    def hotspots_for(self, module_path: str) -> list[ArchHotspot]:
        """Return hotspots whose path starts with *module_path*."""
        return [h for h in self.hotspots if h.path.startswith(module_path)]

    def abstractions_in(self, module_path: str) -> list[ArchAbstraction]:
        """Return abstractions whose module_path matches."""
        return [a for a in self.abstractions if a.module_path == module_path]

    # -- serialization -------------------------------------------------------

    _SCHEMA_VERSION = 1

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-safe dictionary."""
        return {
            "_schema_v": self._SCHEMA_VERSION,
            "version": self.version,
            "updated_at": self.updated_at,
            "modules": [
                {
                    "path": m.path,
                    "drift_score": m.drift_score,
                    "file_count": m.file_count,
                    "function_count": m.function_count,
                    "responsibility": m.responsibility,
                    "layer": m.layer,
                    "primary_owner": m.primary_owner,
                    "stability": m.stability,
                    "signal_scores": m.signal_scores,
                    "languages": m.languages,
                }
                for m in self.modules
            ],
            "dependencies": [
                {
                    "from_module": d.from_module,
                    "to_module": d.to_module,
                    "dep_type": d.dep_type,
                    "weight": d.weight,
                    "policy": d.policy,
                }
                for d in self.dependencies
            ],
            "abstractions": [
                {
                    "symbol": a.symbol,
                    "kind": a.kind,
                    "module_path": a.module_path,
                    "file_path": a.file_path,
                    "usage_count": a.usage_count,
                    "consumers": a.consumers,
                    "has_docstring": a.has_docstring,
                    "is_exported": a.is_exported,
                }
                for a in self.abstractions
            ],
            "hotspots": [
                {
                    "path": h.path,
                    "recurring_signals": h.recurring_signals,
                    "trend": h.trend,
                    "total_occurrences": h.total_occurrences,
                }
                for h in self.hotspots
            ],
            "decisions": [
                {
                    "id": dec.id,
                    "scope": dec.scope,
                    "rule": dec.rule,
                    "enforcement": dec.enforcement,
                    "source": dec.source,
                    "active": dec.active,
                }
                for dec in self.decisions
            ],
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ArchGraph:
        """Deserialize from a dictionary (inverse of *to_dict*)."""
        return cls(
            version=data["version"],
            updated_at=data.get("updated_at", time.time()),
            modules=[
                ArchModule(
                    path=m["path"],
                    drift_score=m["drift_score"],
                    file_count=m["file_count"],
                    function_count=m["function_count"],
                    responsibility=m.get("responsibility"),
                    layer=m.get("layer"),
                    primary_owner=m.get("primary_owner"),
                    stability=m.get("stability", 1.0),
                    signal_scores=m.get("signal_scores", {}),
                    languages=m.get("languages", []),
                )
                for m in data.get("modules", [])
            ],
            dependencies=[
                ArchDependency(
                    from_module=d["from_module"],
                    to_module=d["to_module"],
                    dep_type=d.get("dep_type", "import"),
                    weight=d.get("weight", 1),
                    policy=d.get("policy"),
                )
                for d in data.get("dependencies", [])
            ],
            abstractions=[
                ArchAbstraction(
                    symbol=a["symbol"],
                    kind=a["kind"],
                    module_path=a["module_path"],
                    file_path=a["file_path"],
                    usage_count=a.get("usage_count", 0),
                    consumers=a.get("consumers", []),
                    has_docstring=a.get("has_docstring", False),
                    is_exported=a.get("is_exported", False),
                )
                for a in data.get("abstractions", [])
            ],
            hotspots=[
                ArchHotspot(
                    path=h["path"],
                    recurring_signals=h.get("recurring_signals", {}),
                    trend=h.get("trend", "stable"),
                    total_occurrences=h.get("total_occurrences", 0),
                )
                for h in data.get("hotspots", [])
            ],
            decisions=[
                ArchDecision(
                    id=dec["id"],
                    scope=dec["scope"],
                    rule=dec["rule"],
                    enforcement=dec.get("enforcement", "warn"),
                    source=dec.get("source"),
                    active=dec.get("active", True),
                )
                for dec in data.get("decisions", [])
            ],
        )
