#!/usr/bin/env python3
"""Regression guard for the negative-pattern library.

For every pattern with ``tp_confirmed: true``, materializes the pattern files
in a temporary directory, runs ``drift analyze``, and checks that the expected
signal fires.  Generates ``data/negative-patterns/METRICS.md`` with per-signal
precision and a per-pattern detection table.

Exit code 0 = all confirmed patterns detected, 1 = regression(s) found.

Usage::

    python scripts/check_negative_patterns.py          # run + generate METRICS.md
    python scripts/check_negative_patterns.py --check   # run only, skip METRICS
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PATTERNS_DIR = REPO_ROOT / "data" / "negative-patterns" / "patterns"
METRICS_PATH = REPO_ROOT / "data" / "negative-patterns" / "METRICS.md"


def _find_python() -> str:
    """Return the Python executable used for this process."""
    return sys.executable


def _collect_patterns() -> list[dict]:
    """Load all pattern metadata JSON files."""
    patterns = []
    for jf in sorted(PATTERNS_DIR.rglob("*.json")):
        data = json.loads(jf.read_text(encoding="utf-8"))
        data["_json_path"] = jf
        patterns.append(data)
    return patterns


def _collect_py_files(pattern_id: str) -> list[Path]:
    """Collect .py files belonging to a pattern."""
    # Multi-file: directory named after pattern_id
    pattern_dir = PATTERNS_DIR / pattern_id
    if pattern_dir.is_dir():
        return sorted(pattern_dir.glob("*.py"))
    # Single-file
    single = PATTERNS_DIR / f"{pattern_id}.py"
    if single.exists():
        return [single]
    return []


def _run_drift_analyze(target_dir: Path) -> list[dict]:
    """Run drift analyze on a directory and return findings as dicts."""
    python = _find_python()
    result = subprocess.run(
        [python, "-m", "drift", "analyze", "--repo", str(target_dir),
         "--format", "json", "--exit-zero"],
        capture_output=True,
        text=True,
        timeout=120,
    )
    if result.returncode != 0:
        print(f"  WARNING: drift analyze exited {result.returncode}", file=sys.stderr)
        if result.stderr:
            for line in result.stderr.strip().splitlines()[:5]:
                print(f"    {line}", file=sys.stderr)

    # Extract JSON from output (may have trailing Rich console text)
    stdout = result.stdout.strip()
    if not stdout:
        return []
    # Find the JSON object boundaries
    first_brace = stdout.find("{")
    last_brace = stdout.rfind("}")
    if first_brace == -1 or last_brace == -1:
        return []
    try:
        data = json.loads(stdout[first_brace:last_brace + 1])
    except json.JSONDecodeError:
        return []
    return data.get("findings", [])


def _check_pattern(pattern: dict) -> bool:
    """Check if drift detects a single pattern.  Returns True if detected."""
    pattern_id = pattern["id"]
    expected_signal = pattern["signal"]
    py_files = _collect_py_files(pattern_id)

    if not py_files:
        print(f"  SKIP {pattern_id}: no .py files found", file=sys.stderr)
        return False

    with tempfile.TemporaryDirectory(prefix=f"drift_np_{pattern_id}_") as tmpdir:
        tmppath = Path(tmpdir)

        # For multi-file patterns, preserve directory structure
        src_dir = PATTERNS_DIR / pattern_id
        if src_dir.is_dir():
            for py_file in py_files:
                dest = tmppath / py_file.name
                shutil.copy2(py_file, dest)
        else:
            # Single file — copy to tmpdir
            shutil.copy2(py_files[0], tmppath / py_files[0].name)

        findings = _run_drift_analyze(tmppath)

    # Check if expected signal appears in findings
    for f in findings:
        signal_value = f.get("signal", "")
        if signal_value == expected_signal:
            return True
    return False


def _generate_metrics(results: list[dict]) -> str:
    """Generate METRICS.md content from check results."""
    lines = [
        "# Negative-Pattern Library — Metrics",
        "",
        f"> Auto-generated by `scripts/check_negative_patterns.py` on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "## Per-Pattern Detection",
        "",
        "| Pattern ID | Signal | Severity | TP Confirmed | Detected |",
        "|---|---|---|---|---|",
    ]

    by_signal: dict[str, dict[str, int]] = defaultdict(lambda: {"tp": 0, "fn": 0, "total": 0})

    for r in results:
        detected_str = "✅" if r["detected"] else "❌"
        lines.append(
            f"| `{r['id']}` | {r['signal']} | {r['severity']} "
            f"| {r['tp_confirmed']} | {detected_str} |"
        )
        if r["tp_confirmed"]:
            by_signal[r["signal"]]["total"] += 1
            if r["detected"]:
                by_signal[r["signal"]]["tp"] += 1
            else:
                by_signal[r["signal"]]["fn"] += 1

    lines.extend([
        "",
        "## Per-Signal Precision",
        "",
        "| Signal | TP | FN | Precision |",
        "|---|---|---|---|",
    ])

    for signal in sorted(by_signal):
        s = by_signal[signal]
        precision = s["tp"] / s["total"] if s["total"] > 0 else 0.0
        lines.append(f"| {signal} | {s['tp']} | {s['fn']} | {precision:.2f} |")

    # Overall
    total_tp = sum(s["tp"] for s in by_signal.values())
    total_all = sum(s["total"] for s in by_signal.values())
    overall = total_tp / total_all if total_all > 0 else 0.0
    lines.extend([
        "",
        f"**Overall detection rate:** {total_tp}/{total_all} ({overall:.0%})",
        "",
    ])

    return "\n".join(lines) + "\n"


def main() -> int:
    check_only = "--check" in sys.argv

    patterns = _collect_patterns()
    if not patterns:
        print("ERROR: No patterns found", file=sys.stderr)
        return 1

    tp_patterns = [p for p in patterns if p.get("tp_confirmed")]
    print(f"Checking {len(tp_patterns)} confirmed patterns...")

    results: list[dict] = []
    regressions: list[str] = []

    for p in patterns:
        is_tp = p.get("tp_confirmed", False)
        detected = False

        if is_tp:
            detected = _check_pattern(p)
            status = "✓" if detected else "✗ REGRESSION"
            print(f"  {status}: {p['id']} ({p['signal']})")
            if not detected:
                regressions.append(p["id"])

        results.append({
            "id": p["id"],
            "signal": p["signal"],
            "severity": p.get("severity", "unknown"),
            "tp_confirmed": is_tp,
            "detected": detected,
        })

    # Generate METRICS.md
    if not check_only:
        metrics_content = _generate_metrics(results)
        METRICS_PATH.write_text(metrics_content, encoding="utf-8")
        print(f"\n✓ METRICS.md generated at {METRICS_PATH}")

    # Report
    if regressions:
        print(
            f"\n✗ REGRESSION: {len(regressions)} pattern(s) no longer detected:",
            file=sys.stderr,
        )
        for r in regressions:
            print(f"  • {r}", file=sys.stderr)
        return 1

    print(f"\n✓ All {len(tp_patterns)} confirmed patterns detected successfully")
    return 0


if __name__ == "__main__":
    sys.exit(main())
