"""``drift init`` — scaffold drift configuration and CI integration.

Generates drift.yaml (with optional profile), GitHub Actions workflow,
git hooks, VS Code MCP configuration, and a Claude Desktop MCP snippet.
"""

from __future__ import annotations

import json
import shutil
import sys
import textwrap
from pathlib import Path

import click
import yaml  # type: ignore[import-untyped]

from drift.commands import console
from drift.profiles import PROFILES, get_profile

# ---------------------------------------------------------------------------
# Template constants
# ---------------------------------------------------------------------------

_GITHUB_WORKFLOW = textwrap.dedent("""\
    # Drift — Architectural Drift Check (generated by drift init)
    name: "Drift Gate"

    on:
      pull_request:
        branches: [main, master]
      push:
        branches: [main, master]

    permissions:
      contents: read
      security-events: write
      pull-requests: write

    jobs:
      drift-check:
        name: Architectural Drift Check
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - uses: mick-gsk/drift@v1
            id: drift
            with:
              fail-on: "{fail_on}"
              upload-sarif: "true"
              comment: "true"
              since: "90"
          - name: Summary
            if: always()
            run: |
              echo "### Drift Results" >> $GITHUB_STEP_SUMMARY
              SCORE=${{{{ steps.drift.outputs.drift-score }}}}
              COUNT=${{{{ steps.drift.outputs.finding-count }}}}
              SEV=${{{{ steps.drift.outputs.severity }}}}
              echo "- **Score:** $SCORE" >> $GITHUB_STEP_SUMMARY
              echo "- **Findings:** $COUNT" >> $GITHUB_STEP_SUMMARY
              echo "- **Severity:** $SEV" >> $GITHUB_STEP_SUMMARY
""")


_PRE_PUSH_HOOK = textwrap.dedent("""\
    #!/usr/bin/env sh
    # Drift pre-push hook (generated by drift init)
    set -e

    if [ "${{DRIFT_SKIP_CHECK:-0}}" = "1" ]; then
        echo ">>> [drift] WARN: drift check skipped (DRIFT_SKIP_CHECK=1)"
        exit 0
    fi

    if ! command -v drift >/dev/null 2>&1; then
        echo ">>> [drift] WARN: drift-analyzer not installed, skipping"
        exit 0
    fi

    echo ">>> [drift] Running architectural drift check..."
    if drift check --diff HEAD~1 --fail-on {fail_on} --quiet 2>/dev/null; then
        echo ">>> [drift] OK"
    else
        exit_code=$?
        echo ">>> [drift] BLOCKED — run 'drift analyze' for full report"
        exit $exit_code
    fi
""")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _resolve_mcp_launcher() -> tuple[str, list[str], str]:
    """Resolve the lowest-friction launcher for generated MCP configs."""
    if shutil.which("drift"):
        return "drift", ["mcp", "--serve"], "console-script"
    if shutil.which("drift-analyzer"):
        return "drift-analyzer", ["mcp", "--serve"], "console-script"
    return sys.executable, ["-m", "drift", "mcp", "--serve"], "python-module"


def _render_mcp_json(*, claude: bool, command: str, args: list[str]) -> str:
    """Render MCP JSON for the target client using the resolved launcher."""
    if claude:
        payload = {
            "mcpServers": {
                "drift": {
                    "command": command,
                    "args": args,
                }
            }
        }
    else:
        payload = {
            "servers": {
                "drift": {
                    "type": "stdio",
                    "command": command,
                    "args": args,
                }
            }
        }
    return json.dumps(payload, indent=2) + "\n"


def _build_config_dict(profile_name: str) -> dict:
    """Build a drift.yaml-compatible dict from a named profile."""
    profile = get_profile(profile_name)
    cfg: dict = {}

    cfg["include"] = ["**/*.py", "**/*.ts", "**/*.tsx"]
    cfg["exclude"] = [
        "**/node_modules/**",
        "**/__pycache__/**",
        "**/venv/**",
        "**/.venv/**",
        "**/.tmp_*venv*/**",
        "**/.env/**",
        "**/.conda/**",
        "**/.git/**",
        "**/dist/**",
        "**/build/**",
        "**/.tox/**",
        "**/.nox/**",
        "**/site-packages/**",
        "**/.pixi/**",
        "**/*.egg-info/**",
        "**/docs/**",
        "**/docs_src/**",
        "**/examples/**",
        "**/tests/**",
        "**/scripts/**",
        "**/site/**",
    ]

    cfg["weights"] = dict(profile.weights)
    cfg["auto_calibrate"] = profile.auto_calibrate
    cfg["fail_on"] = profile.fail_on

    if profile.thresholds:
        cfg["thresholds"] = dict(profile.thresholds)

    if profile.policies:
        cfg["policies"] = dict(profile.policies)

    return cfg


def _yaml_header(profile_name: str) -> str:
    """Return a YAML comment header identifying the profile."""
    profile = get_profile(profile_name)
    return (
        f"# Drift configuration — profile: {profile.name}\n"
        f"# {profile.description}\n"
        f"# Generated by: drift init --profile {profile.name}\n\n"
    )


def _write_if_absent(path: Path, content: str, label: str, *, root: Path | None = None) -> bool:
    """Write *content* to *path* if it does not already exist.

    Returns True if the file was created, False if it was skipped.
    """
    display = path.relative_to(root) if root else path.name
    if path.exists():
        console.print(f"  [yellow]skip[/yellow]  {display} (already exists)")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    console.print(f"  [green]create[/green] {display}")
    return True


def _plan_file(
    plan: list[dict[str, object]],
    target: Path,
    content: str,
    repo_root: Path,
) -> None:
    """Append a file-creation plan entry (no I/O)."""
    rel = str(target.relative_to(repo_root)).replace("\\", "/")
    plan.append({
        "path": rel,
        "size_bytes": len(content.encode("utf-8")),
        "exists": target.exists(),
        "content": content,
    })


# ---------------------------------------------------------------------------
# CLI command
# ---------------------------------------------------------------------------


@click.command("init")
@click.option(
    "--profile",
    "-p",
    type=click.Choice(sorted(PROFILES.keys()), case_sensitive=False),
    default="default",
    help="Configuration profile to use.",
    show_default=True,
)
@click.option(
    "--ci",
    is_flag=True,
    default=False,
    help="Generate GitHub Actions workflow (.github/workflows/drift.yml).",
)
@click.option(
    "--hooks",
    is_flag=True,
    default=False,
    help="Generate git pre-push hook (.githooks/drift-pre-push).",
)
@click.option(
    "--mcp",
    is_flag=True,
    default=False,
    help="Generate VS Code MCP server config (.vscode/mcp.json).",
)
@click.option(
    "--claude",
    is_flag=True,
    default=False,
    help=(
        "Generate Claude Desktop MCP config snippet "
        "(claude_desktop_config.json)."
    ),
)
@click.option(
    "--full",
    is_flag=True,
    default=False,
    help="Generate all files: config + CI + hooks + MCP + Claude snippet.",
)
@click.option(
    "--dry-run",
    is_flag=True,
    default=False,
    help="Preview which files would be created without writing anything.",
)
@click.option(
    "--json",
    "json_output",
    is_flag=True,
    default=False,
    help="Output dry-run preview as JSON (implies --dry-run).",
)
@click.option(
    "--interactive",
    "-i",
    is_flag=True,
    default=False,
    help="Ask 3 simple questions to choose the best profile (like drift setup).",
)
@click.option(
    "--repo",
    "-r",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    default=".",
    help="Repository root.",
)
def init(
    profile: str,
    ci: bool,
    hooks: bool,
    mcp: bool,
    claude: bool,
    full: bool,
    dry_run: bool,
    json_output: bool,
    interactive: bool,
    repo: Path,
) -> None:
    """Scaffold drift configuration and CI integration.

    Generates a drift.yaml with the chosen profile, plus optional
    GitHub Actions workflow, git hooks, and editor/agent integration.

    \b
    Examples:
      drift init                          # default profile, config only
      drift init --profile vibe-coding    # AI-optimised weights
            drift init --full                   # config + CI + hooks + MCP + Claude
      drift init -p vibe-coding --ci      # vibe-coding config + CI workflow
            drift init --mcp --claude           # scaffold VS Code + Claude MCP configs
      drift init --full --dry-run         # preview without writing
      drift init --full --json            # JSON preview for agents
      drift init --interactive --full     # guided profile + full scaffolding
    """
    repo = repo.resolve()

    if json_output:
        dry_run = True

    if full:
        ci = hooks = mcp = claude = True

    # --interactive: use setup questions to derive best-fit profile
    if interactive and not json_output:
        from drift.commands.setup import (
            _ask_ai_usage,
            _ask_project_type,
            _ask_strictness,
            _derive_profile,
            _detect_language,
        )

        lang = _detect_language()
        console.print()
        if lang.startswith("de"):
            console.print("  [bold]drift init --interactive[/bold] — Profil in 3 Fragen")
        else:
            console.print("  [bold]drift init --interactive[/bold] — choose profile in 3 questions")
        console.print("  " + "\u2500" * 45)
        console.print()
        project_type = _ask_project_type(lang)
        ai_usage = _ask_ai_usage(lang)
        strictness = _ask_strictness(lang)
        profile = _derive_profile(project_type, ai_usage, strictness)

    prof = get_profile(profile)
    launcher_command, launcher_args, launcher_source = _resolve_mcp_launcher()

    # Collect file plan
    plan: list[dict[str, object]] = []

    # 1. drift.yaml
    config_dict = _build_config_dict(profile)
    config_yaml = _yaml_header(profile) + yaml.dump(
        config_dict, default_flow_style=False, sort_keys=False, allow_unicode=True,
    )
    _plan_file(plan, repo / "drift.yaml", config_yaml, repo)

    # 2. GitHub Actions workflow
    if ci:
        fail_on = "none" if profile != "strict" else "medium"
        workflow_content = _GITHUB_WORKFLOW.format(fail_on=fail_on)
        workflow_path = repo / ".github" / "workflows" / "drift.yml"
        _plan_file(plan, workflow_path, workflow_content, repo)

    # 3. Git pre-push hook
    if hooks:
        hook_fail = "high" if profile != "strict" else "medium"
        hook_content = _PRE_PUSH_HOOK.format(fail_on=hook_fail)
        hook_path = repo / ".githooks" / "drift-pre-push"
        _plan_file(plan, hook_path, hook_content, repo)

    # 4. VS Code MCP config
    if mcp:
        mcp_path = repo / ".vscode" / "mcp.json"
        _plan_file(
            plan,
            mcp_path,
            _render_mcp_json(
                claude=False,
                command=launcher_command,
                args=launcher_args,
            ),
            repo,
        )

    # 5. Claude Desktop MCP snippet
    if claude:
        claude_path = repo / "claude_desktop_config.json"
        _plan_file(
            plan,
            claude_path,
            _render_mcp_json(
                claude=True,
                command=launcher_command,
                args=launcher_args,
            ),
            repo,
        )

    # --dry-run / --json: preview only, no file writes
    if dry_run:
        skip_count = sum(1 for p in plan if p["exists"])
        new_count = sum(1 for p in plan if not p["exists"])
        if json_output:
            click.echo(json.dumps({
                "would_create": [
                    {
                        "path": p["path"],
                        "size_bytes": p["size_bytes"],
                        "exists": p["exists"],
                        "action": "skip" if p["exists"] else "create",
                        "would_skip": p["exists"],
                        "would_overwrite": False,
                    }
                    for p in plan
                ],
                "overwrite_count": 0,
                "skip_count": skip_count,
                "new_count": new_count,
            }, indent=2))
        else:
            console.print(
                f"[bold]Dry run[/bold] — profile "
                f"[cyan]{prof.name}[/cyan]: {prof.description}\n"
            )
            for p in plan:
                status = "[yellow]skip[/yellow]" if p["exists"] else "[green]create[/green]"
                console.print(f"  {status}  {p['path']}  ({p['size_bytes']} bytes)")
            console.print(
                f"\n[dim]{new_count} new, {skip_count} would skip[/dim]"
            )
        return

    # Normal mode: write files
    console.print(
        f"[bold]Initialising drift[/bold] with profile "
        f"[cyan]{prof.name}[/cyan]: {prof.description}\n"
    )

    created = 0
    printed_mcp_note = False
    for p in plan:
        target = repo / str(p["path"])
        if _write_if_absent(target, str(p["content"]), str(p["path"]), root=repo):
            created += 1
            if "drift-pre-push" in str(p["path"]):
                console.print(
                    "  [dim]Activate with: "
                    "git config core.hooksPath .githooks[/dim]"
                )
            if not printed_mcp_note and str(p["path"]) in {
                ".vscode/mcp.json",
                "claude_desktop_config.json",
            }:
                console.print(
                    "  Requires MCP extra: pip install drift-analyzer[mcp]",
                    style="dim",
                    markup=False,
                )
                if launcher_source == "python-module":
                    console.print(
                        "  [dim]No drift executable found on PATH; generated config "
                        "uses the current Python interpreter.[/dim]"
                    )
                    if hooks:
                        console.print(
                            "  [dim]The generated pre-push hook still expects "
                            "`drift` on PATH.[/dim]"
                        )
                printed_mcp_note = True
            if str(p["path"]) == "claude_desktop_config.json":
                console.print(
                    "  [dim]Windows merge target: "
                    "%APPDATA%\\Claude\\claude_desktop_config.json[/dim]"
                )
                console.print(
                    "  [dim]macOS merge target: "
                    "~/Library/Application Support/Claude/claude_desktop_config.json[/dim]"
                )
                console.print(
                    "  [dim]macOS merge target: "
                    "~/Library/Application Support/Claude/claude_desktop_config.json[/dim]"
                )

    # Summary
    console.print()
    ascii_only = bool(getattr(console, "_drift_ascii_only", False))
    ok_marker = "OK" if ascii_only else "✓"
    arrow = "->" if ascii_only else "→"
    dash = " - " if ascii_only else " — "

    if created:
        console.print(f"[bold green]{ok_marker} {created} file(s) created.[/bold green]")
        console.print("\nNext steps:")
        console.print("  1. Review drift.yaml and adjust weights if needed")
        console.print("  2. Run [bold]drift analyze[/bold] to see your baseline score")
        console.print("  3. Run [bold]drift baseline save[/bold] to lock the current state")
        if profile == "vibe-coding":
            console.print(
                f"  4. Gradually escalate fail_on: none {arrow} high {arrow} medium over 4 weeks"
            )
    else:
        console.print(f"[yellow]No files created{dash}all targets already exist.[/yellow]")
