"""``drift init`` — scaffold drift configuration and CI integration.

Generates drift.yaml (with optional profile), GitHub Actions workflow,
git hooks, and VS Code MCP configuration in one command.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

import click
import yaml  # type: ignore[import-untyped]

from drift.commands import console
from drift.profiles import PROFILES, get_profile

# ---------------------------------------------------------------------------
# Template constants
# ---------------------------------------------------------------------------

_GITHUB_WORKFLOW = textwrap.dedent("""\
    # Drift — Architectural Drift Check (generated by drift init)
    name: "Drift Gate"

    on:
      pull_request:
        branches: [main, master]
      push:
        branches: [main, master]

    permissions:
      contents: read
      security-events: write
      pull-requests: write

    jobs:
      drift-check:
        name: Architectural Drift Check
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - uses: sauremilk/drift@v1
            id: drift
            with:
              fail-on: "{fail_on}"
              upload-sarif: "true"
              comment: "true"
              since: "90"
          - name: Summary
            if: always()
            run: |
              echo "### Drift Results" >> $GITHUB_STEP_SUMMARY
              SCORE=${{{{ steps.drift.outputs.drift-score }}}}
              COUNT=${{{{ steps.drift.outputs.finding-count }}}}
              SEV=${{{{ steps.drift.outputs.severity }}}}
              echo "- **Score:** $SCORE" >> $GITHUB_STEP_SUMMARY
              echo "- **Findings:** $COUNT" >> $GITHUB_STEP_SUMMARY
              echo "- **Severity:** $SEV" >> $GITHUB_STEP_SUMMARY
""")


_PRE_PUSH_HOOK = textwrap.dedent("""\
    #!/usr/bin/env sh
    # Drift pre-push hook (generated by drift init)
    set -e

    if [ "${{DRIFT_SKIP_CHECK:-0}}" = "1" ]; then
        echo ">>> [drift] WARN: drift check skipped (DRIFT_SKIP_CHECK=1)"
        exit 0
    fi

    if ! command -v drift >/dev/null 2>&1; then
        echo ">>> [drift] WARN: drift-analyzer not installed, skipping"
        exit 0
    fi

    echo ">>> [drift] Running architectural drift check..."
    if drift check --diff HEAD~1 --fail-on {fail_on} --quiet 2>/dev/null; then
        echo ">>> [drift] OK"
    else
        exit_code=$?
        echo ">>> [drift] BLOCKED — run 'drift analyze' for full report"
        exit $exit_code
    fi
""")


_MCP_JSON = textwrap.dedent("""\
    {
      "servers": {
        "drift": {
          "type": "stdio",
          "command": "drift",
          "args": ["mcp", "--serve"]
        }
      }
    }
""")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _build_config_dict(profile_name: str) -> dict:
    """Build a drift.yaml-compatible dict from a named profile."""
    profile = get_profile(profile_name)
    cfg: dict = {}

    cfg["include"] = ["**/*.py", "**/*.ts", "**/*.tsx"]
    cfg["exclude"] = [
        "**/node_modules/**",
        "**/__pycache__/**",
        "**/venv/**",
        "**/.venv/**",
        "**/dist/**",
        "**/build/**",
        "**/.git/**",
        "**/*.egg-info/**",
        "**/docs/**",
        "**/examples/**",
    ]

    cfg["weights"] = dict(profile.weights)
    cfg["auto_calibrate"] = profile.auto_calibrate
    cfg["fail_on"] = profile.fail_on

    if profile.thresholds:
        cfg["thresholds"] = dict(profile.thresholds)

    if profile.policies:
        cfg["policies"] = dict(profile.policies)

    return cfg


def _yaml_header(profile_name: str) -> str:
    """Return a YAML comment header identifying the profile."""
    profile = get_profile(profile_name)
    return (
        f"# Drift configuration — profile: {profile.name}\n"
        f"# {profile.description}\n"
        f"# Generated by: drift init --profile {profile.name}\n\n"
    )


def _write_if_absent(path: Path, content: str, label: str, *, root: Path | None = None) -> bool:
    """Write *content* to *path* if it does not already exist.

    Returns True if the file was created, False if it was skipped.
    """
    display = path.relative_to(root) if root else path.name
    if path.exists():
        console.print(f"  [yellow]skip[/yellow]  {display} (already exists)")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    console.print(f"  [green]create[/green] {display}")
    return True


def _plan_file(
    plan: list[dict[str, object]],
    target: Path,
    content: str,
    repo_root: Path,
) -> None:
    """Append a file-creation plan entry (no I/O)."""
    rel = str(target.relative_to(repo_root)).replace("\\", "/")
    plan.append({
        "path": rel,
        "size_bytes": len(content.encode("utf-8")),
        "exists": target.exists(),
        "content": content,
    })


# ---------------------------------------------------------------------------
# CLI command
# ---------------------------------------------------------------------------


@click.command("init")
@click.option(
    "--profile",
    "-p",
    type=click.Choice(sorted(PROFILES.keys()), case_sensitive=False),
    default="default",
    help="Configuration profile to use.",
    show_default=True,
)
@click.option(
    "--ci",
    is_flag=True,
    default=False,
    help="Generate GitHub Actions workflow (.github/workflows/drift.yml).",
)
@click.option(
    "--hooks",
    is_flag=True,
    default=False,
    help="Generate git pre-push hook (.githooks/drift-pre-push).",
)
@click.option(
    "--mcp",
    is_flag=True,
    default=False,
    help="Generate VS Code MCP server config (.vscode/mcp.json).",
)
@click.option(
    "--full",
    is_flag=True,
    default=False,
    help="Generate all files: config + CI + hooks + MCP.",
)
@click.option(
    "--dry-run",
    is_flag=True,
    default=False,
    help="Preview which files would be created without writing anything.",
)
@click.option(
    "--json",
    "json_output",
    is_flag=True,
    default=False,
    help="Output dry-run preview as JSON (implies --dry-run).",
)
@click.option(
    "--repo",
    "-r",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    default=".",
    help="Repository root.",
)
def init(
    profile: str,
    ci: bool,
    hooks: bool,
    mcp: bool,
    full: bool,
    dry_run: bool,
    json_output: bool,
    repo: Path,
) -> None:
    """Scaffold drift configuration and CI integration.

    Generates a drift.yaml with the chosen profile, plus optional
    GitHub Actions workflow, git hooks, and IDE integration.

    \b
    Examples:
      drift init                          # default profile, config only
      drift init --profile vibe-coding    # AI-optimised weights
      drift init --full                   # config + CI + hooks + MCP
      drift init -p vibe-coding --ci      # vibe-coding config + CI workflow
      drift init --full --dry-run         # preview without writing
      drift init --full --json            # JSON preview for agents
    """
    import json as json_mod

    repo = repo.resolve()

    if json_output:
        dry_run = True

    if full:
        ci = hooks = mcp = True

    prof = get_profile(profile)

    # Collect file plan
    plan: list[dict[str, object]] = []

    # 1. drift.yaml
    config_dict = _build_config_dict(profile)
    config_yaml = _yaml_header(profile) + yaml.dump(
        config_dict, default_flow_style=False, sort_keys=False, allow_unicode=True,
    )
    _plan_file(plan, repo / "drift.yaml", config_yaml, repo)

    # 2. GitHub Actions workflow
    if ci:
        fail_on = "none" if profile != "strict" else "medium"
        workflow_content = _GITHUB_WORKFLOW.format(fail_on=fail_on)
        workflow_path = repo / ".github" / "workflows" / "drift.yml"
        _plan_file(plan, workflow_path, workflow_content, repo)

    # 3. Git pre-push hook
    if hooks:
        hook_fail = "high" if profile != "strict" else "medium"
        hook_content = _PRE_PUSH_HOOK.format(fail_on=hook_fail)
        hook_path = repo / ".githooks" / "drift-pre-push"
        _plan_file(plan, hook_path, hook_content, repo)

    # 4. VS Code MCP config
    if mcp:
        mcp_path = repo / ".vscode" / "mcp.json"
        _plan_file(plan, mcp_path, _MCP_JSON, repo)

    # --dry-run / --json: preview only, no file writes
    if dry_run:
        overwrite_count = sum(1 for p in plan if p["exists"])
        new_count = sum(1 for p in plan if not p["exists"])
        if json_output:
            click.echo(json_mod.dumps({
                "would_create": [
                    {
                        "path": p["path"],
                        "size_bytes": p["size_bytes"],
                        "exists": p["exists"],
                        "would_overwrite": p["exists"],
                    }
                    for p in plan
                ],
                "overwrite_count": overwrite_count,
                "new_count": new_count,
            }, indent=2))
        else:
            console.print(
                f"[bold]Dry run[/bold] — profile "
                f"[cyan]{prof.name}[/cyan]: {prof.description}\n"
            )
            for p in plan:
                status = "[yellow]overwrite[/yellow]" if p["exists"] else "[green]create[/green]"
                console.print(f"  {status}  {p['path']}  ({p['size_bytes']} bytes)")
            console.print(
                f"\n[dim]{new_count} new, {overwrite_count} would overwrite[/dim]"
            )
        return

    # Normal mode: write files
    console.print(
        f"[bold]Initialising drift[/bold] with profile "
        f"[cyan]{prof.name}[/cyan]: {prof.description}\n"
    )

    created = 0
    for p in plan:
        target = repo / p["path"]
        if _write_if_absent(target, p["content"], p["path"], root=repo):
            created += 1
            if "drift-pre-push" in str(p["path"]):
                console.print(
                    "  [dim]Activate with: "
                    "git config core.hooksPath .githooks[/dim]"
                )

    # Summary
    console.print()
    if created:
        console.print(f"[bold green]✓ {created} file(s) created.[/bold green]")
        console.print("\nNext steps:")
        console.print("  1. Review drift.yaml and adjust weights if needed")
        console.print("  2. Run [bold]drift analyze[/bold] to see your baseline score")
        console.print("  3. Run [bold]drift baseline save[/bold] to lock the current state")
        if profile == "vibe-coding":
            console.print(
                "  4. Gradually escalate fail_on: none → high → medium over 4 weeks"
            )
    else:
        console.print("[yellow]No files created — all targets already exist.[/yellow]")
